{
 "title": "Cosmos",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cendermint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "cendermint_chain_blockHeight{}", "legendFormat": "Exporter" },
    {
     "expr": "cendermint_validator_last_signed_height{}",
     "legendFormat": "Last Signed"
    }
   ]
  },
  {
   "title": "Stake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cendermint_staking_total_supply{}",
     "legendFormat": "Total"
    },
    {
     "expr": "cendermint_staking_bonded_tokens{}",
     "legendFormat": "Bonded"
    },
    {
     "expr": "cendermint_staking_not_bonded_tokens{}",
     "legendFormat": "Unbonded"
    }
   ]
  },
  {
   "title": "Precommit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "cendermint_validator_precommit_status{}",
     "legendFormat": "Precommit"
    }
   ]
  },
  {
   "title": "Avg TPS per Block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cendermint_tx_tps{}", "legendFormat": "TPS" }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_validator_voting_power{}"
    }
   ]
  },
  {
   "title": "Network Share",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_validator_delegation_ratio{}*100"
    }
   ]
  },
  {
   "title": "Start Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_slashing_start_Height{}"
    }
   ]
  },
  {
   "title": "Tombstoned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_slashing_tombstoned{}"
    }
   ]
  },
  {
   "title": "Block Proposals & Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "cendermint_validator_proposer_status{}",
     "legendFormat": "Proposer"
    },
    {
     "expr": "cendermint_validator_miss_threshold{}",
     "legendFormat": "Miss Since Last Sign > Threshold"
    },
    {
     "expr": "cendermint_validator_miss_consecutive{}",
     "legendFormat": "Consecutive Miss > Threshold"
    }
   ]
  },
  {
   "title": "Jailed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_validator_jail_status{}"
    }
   ]
  },
  {
   "title": "Last Jail End Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_slashing_jailed_until{}*1000"
    }
   ]
  },
  {
   "title": "Missed Blocks per Window",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_slashing_missed_blocks_counter{}"
    }
   ]
  },
  {
   "title": "Bonding Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_staking_bonded_ratio{}*100"
    }
   ]
  },
  {
   "title": "Jail Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_slashing_downtime_jail_duration{}"
    }
   ]
  },
  {
   "title": "Min Signed per Window",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_slashing_min_signed_per_window{}*100"
    }
   ]
  },
  {
   "title": "Double Sign Slash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_slashing_slash_fraction_double_sign{}*100"
    }
   ]
  },
  {
   "title": "Downtime Slash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_slashing_slash_fraction_downtime{}*100"
    }
   ]
  },
  {
   "title": "Node Info (REST)",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "cendermint_labels_node_info{}" }
   ]
  },
  {
   "title": "Inflation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cendermint_minting_actual_inflation{}*100",
     "legendFormat": "Actual"
    },
    {
     "expr": "cendermint_minting_inflation{}*100",
     "legendFormat": "Default"
    }
   ]
  },
  {
   "title": "Proposals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cendermint_gov_voting_proposal_count{}",
     "legendFormat": "In Voting"
    },
    {
     "expr": "cendermint_gov_voting_proposal_did_not_vote_count{}",
     "legendFormat": "Need to vote"
    },
    {
     "expr": "cendermint_gov_total_proposal_count{}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "App Info (REST)",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "cendermint_labels_node_info{}" }
   ]
  },
  {
   "title": "Binary Info (REST)",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "cendermint_labels_node_info{}" }
   ]
  },
  {
   "title": "Addresses",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "cendermint_labels_addr{}" }
   ]
  },
  {
   "title": "IBC  Channels",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cendermint_ibc_channels_total{}",
     "legendFormat": "Total"
    },
    { "expr": "cendermint_ibc_channels_open{}", "legendFormat": "Open" }
   ]
  },
  {
   "title": "IBC Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cendermint_ibc_connections_total{}",
     "legendFormat": "Total"
    },
    {
     "expr": "cendermint_ibc_connections_open{}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Tx Events Default",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "cendermint_tx_events_total{}", "legendFormat": "Total" },
    { "expr": "cendermint_tx_delegate_total{}", "legendFormat": "Delegate" },
    { "expr": "cendermint_tx_message_total{}", "legendFormat": "Message" },
    { "expr": "cendermint_tx_transfer_total{}", "legendFormat": "Transfer" },
    { "expr": "cendermint_tx_unbond_total{}", "legendFormat": "Unbond" },
    {
     "expr": "cendermint_tx_withdraw_rewards_total{}",
     "legendFormat": "Withdraw Rewards"
    },
    {
     "expr": "cendermint_tx_redelegate_total{}",
     "legendFormat": "Redelegate"
    },
    {
     "expr": "cendermint_tx_proposal_vote_total{}",
     "legendFormat": "Vote"
    },
    { "expr": "cendermint_tx_others_total{}", "legendFormat": "Others" }
   ]
  },
  {
   "title": "Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cendermint_tx_gas_used_total{}", "legendFormat": "Gas Used Total" },
    {
     "expr": "cendermint_tx_gas_wanted_total{}",
     "legendFormat": "Gas Limit Total"
    }
   ]
  },
  {
   "title": "Tx Events IBC",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cendermint_tx_ibc_fungible_token_packet_total{}",
     "legendFormat": "Fungible Token Packet"
    },
    {
     "expr": "cendermint_tx_ibc_transfer_total{}",
     "legendFormat": "Transfer"
    },
    {
     "expr": "cendermint_tx_ibc_update_client_total{}",
     "legendFormat": "Update Client"
    },
    {
     "expr": "cendermint_tx_ibc_ack_packet_total{}",
     "legendFormat": "Ack Packet"
    },
    {
     "expr": "cendermint_tx_ibc_send_packet_total{}",
     "legendFormat": "Send Packet"
    },
    {
     "expr": "cendermint_tx_ibc_recv_packet_total{}",
     "legendFormat": "Receive Packet"
    },
    {
     "expr": "cendermint_tx_ibc_timeout_total{}",
     "legendFormat": "Timeout"
    },
    {
     "expr": "cendermint_tx_ibc_timeout_packet_total{}",
     "legendFormat": "Timeout Packet"
    },
    {
     "expr": "cendermint_tx_ibc_denom_trace_total{}",
     "legendFormat": "Denom Trace"
    }
   ]
  },
  {
   "title": "Tx Events Swap",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cendermint_tx_swap_swap_within_batch_total{}",
     "legendFormat": "Swap"
    },
    {
     "expr": "cendermint_tx_swap_deposit_within_batch_total{}",
     "legendFormat": "Deposit"
    },
    {
     "expr": "cendermint_tx_swap_withdraw_within_batch_total{}",
     "legendFormat": "Withdraw"
    }
   ]
  },
  { "title": "Oracle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Misses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_oracle_validators_misses{}"
    }
   ]
  },
  {
   "title": "Submit Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_oracle_validators_submit_block"
    }
   ]
  },
  {
   "title": "Feeder Delegate",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "cendermint_labels_oracle{}" }
   ]
  },
  { "title": "Peggo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Bridge Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_bridge_active{}"
    }
   ]
  },
  {
   "title": "Event Nonce",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_event_nonce{}"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_valset_count{}"
    }
   ]
  },
  {
   "title": "Orchestrator Active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_valset_active{}"
    }
   ]
  },
  {
   "title": "Umee Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_erc20_price{}"
    }
   ]
  },
  {
   "title": "Signed Batches Window",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_signed_batches_window{}"
    }
   ]
  },
  {
   "title": "Signed Valsets Window",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_signed_valsets_window{}"
    }
   ]
  },
  {
   "title": "Bad Eth Sigs Slash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_slash_fraction_bad_eth_sig{}*100"
    }
   ]
  },
  {
   "title": "Batch Slash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_slash_fraction_batch{}*100"
    }
   ]
  },
  {
   "title": "Valsets Slash",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_slash_fraction_valset{}*100"
    }
   ]
  },
  {
   "title": "Batch Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_target_batch_timeout{}"
    }
   ]
  },
  {
   "title": "Reward",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cendermint_gravity_valset_reward_amount{}"
    }
   ]
  },
  {
   "title": "All Batches",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "cendermint_gravity_batches_fees{}",
     "legendFormat": "Fees (USD)"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "cendermint_gravity_batch_fees{}",
     "legendFormat": "Fees (USD)"
    }
   ]
  },
  {
   "title": "Bridge Fees",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cendermint_gravity_bridge_fees{}",
     "legendFormat": "Bridge Fees (umee)"
    }
   ]
  }
 ]
}